// funiber-client/src/components/Footer/Footer.jsx
import React from 'react';

export const Footer = () => {
  return (
    <footer className="bg-gray-500">
      <div className="w-full px-2 py-2 mx-auto sm:px-6 lg:px-4">
        <div className="sm:flex sm:items-center sm:justify-between">
          <p className="mt-4 text-sm text-center text-gray-200 lg:text-right lg:mt-0">
            Copyright &copy; 2022. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
};

// prueba-frontend/fnbr-frontend/src/components/Footer.vue
<template>
    <div class="footer">
        <div class="w-full bg-gray-400 mt-16">
            <div class="container flex flex-col mx-auto">
                <div class="flex flex-col items-start w-full py-5">
                    <div class="flex">
                        <p class="text-base font-normal leading-7 text-center text-white">©
                            Copyright 2005 - 2022. Ibero-American University Fundation - All rights reserved</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: "Footer",
};
</script>
